-- mortgage_applications_secure (view)
-- Captured from production by tools/recapture-db-views.mjs. Do not hand-edit.
--
-- security_invoker: false
--   DEFINER: this view runs as its OWNER and is NOT subject to the base
--   tables' RLS. Anything granted SELECT here reads past that protection.
-- base_tables_with_rls: mortgage_applications
-- base_tables_without_rls: (none)
-- select_granted_to: anon, authenticated, service_role
--
-- !! DEFINER + reads an RLS table + anon can SELECT. This is the
-- !! contacts_live configuration. See tools/check-view-exposure.mjs.
--

create or replace view public.mortgage_applications_secure as
 SELECT id,
    contact_id,
    borrower_user_id,
    status,
    loan_purpose,
    occupancy,
    property_address,
    property_city,
    property_state,
    property_zip,
    estimated_value,
    purchase_price,
    requested_loan_amount,
    created_at,
    updated_at,
    google_drive_folder_url,
    processor_handoff_at,
    processor_email,
    processor_name,
    va_assigned,
    first_name,
    middle_name,
    last_name,
    suffix,
    alternate_names,
        CASE
            WHEN is_admin() OR is_borrower() AND (contact_id = current_contact_id() OR co_borrower_contact_id = current_contact_id()) THEN ssn
            ELSE NULL::text
        END AS ssn,
        CASE
            WHEN is_admin() OR is_borrower() AND (contact_id = current_contact_id() OR co_borrower_contact_id = current_contact_id()) THEN date_of_birth
            ELSE NULL::date
        END AS date_of_birth,
    citizenship,
    credit_type,
    marital_status,
    dependents_count,
    dependents_ages,
    home_phone,
    cell_phone,
    work_phone,
    work_phone_ext,
    email,
    current_address_street,
    current_address_unit,
    current_address_city,
    current_address_state,
    current_address_zip,
    current_address_country,
    current_address_years,
    current_address_months,
    current_housing_type,
    current_rent_amount,
    former_addresses,
    mailing_address_street,
    mailing_address_unit,
    mailing_address_city,
    mailing_address_state,
    mailing_address_zip,
    employments,
    other_income_sources,
    assets,
    other_assets,
    liabilities,
    other_liabilities,
    real_estate_owned,
    loan_amount,
    property_address_street,
    property_address_unit,
    property_address_city,
    property_address_state,
    property_address_zip,
    property_address_county,
    number_of_units,
    property_value,
    occupancy_type,
    mixed_use_property,
    manufactured_home,
    gifts_grants,
    decl_primary_residence,
    decl_ownership_interest,
    decl_family_relationship_seller,
    decl_borrowed_funds,
    decl_borrowed_funds_amount,
    decl_applying_other_mortgage,
    decl_new_credit,
    decl_lien_priority,
    decl_cosigner,
    decl_outstanding_judgments,
    decl_delinquent_federal,
    decl_lawsuit,
    decl_deed_in_lieu,
    decl_short_sale,
    decl_foreclosure,
    decl_bankruptcy,
    decl_bankruptcy_types,
    military_service,
    military_status,
    ethnicity,
    race,
    sex,
    co_borrower,
    lo_org_name,
    lo_org_nmls,
    lo_name,
    lo_nmls,
    lo_email,
    lo_phone,
    mismo_exported_at,
    mismo_version,
    current_housing,
    former_address_street,
    former_address_unit,
    former_address_city,
    former_address_state,
    former_address_zip,
    former_address_years,
    former_address_months,
    former_housing,
    former_rent_amount,
    former_address2_street,
    former_address2_city,
    former_address2_state,
    former_address2_zip,
    employer_name,
    employer_phone,
    employer_street,
    employer_city,
    employer_state,
    employer_zip,
    position_title,
    employment_start_date,
    years_in_line_of_work,
    months_in_line_of_work,
    is_self_employed,
    ownership_share,
    base_income,
    overtime_income,
    bonus_income,
    commission_income,
    military_income,
    other_income,
    total_monthly_income,
    employer2_name,
    employer2_phone,
    employer2_street,
    employer2_city,
    employer2_state,
    employer2_zip,
    position2_title,
    employment2_start_date,
    is_self_employed2,
    base_income2,
    total_monthly_income2,
    prev_employer_name,
    prev_employer_street,
    prev_employer_city,
    prev_employer_state,
    prev_position_title,
    prev_employment_start_date,
    prev_employment_end_date,
    prev_monthly_income,
    was_self_employed_prev,
        CASE
            WHEN is_admin() OR is_borrower() AND (contact_id = current_contact_id() OR co_borrower_contact_id = current_contact_id()) THEN bank_accounts
            ELSE NULL::jsonb
        END AS bank_accounts,
    total_assets,
    owned_properties,
    num_units,
    is_mixed_use,
    is_manufactured_home,
    gift_funds,
    declaration_primary_residence,
    declaration_family_relationship,
    declaration_borrowed_funds,
    declaration_borrowed_amount,
    declaration_other_mortgage,
    declaration_new_credit,
    declaration_lien_priority,
    declaration_cosigner,
    declaration_judgments,
    declaration_delinquent,
    declaration_lawsuit,
    declaration_deed_in_lieu,
    declaration_short_sale,
    declaration_foreclosure,
    declaration_bankruptcy,
    bankruptcy_type,
    military_expiration_date,
    co_borrower_contact_id,
    co_borrower_first_name,
    co_borrower_middle_name,
    co_borrower_last_name,
    co_borrower_suffix,
        CASE
            WHEN is_admin() OR is_borrower() AND (contact_id = current_contact_id() OR co_borrower_contact_id = current_contact_id()) THEN co_borrower_ssn
            ELSE NULL::text
        END AS co_borrower_ssn,
        CASE
            WHEN is_admin() OR is_borrower() AND (contact_id = current_contact_id() OR co_borrower_contact_id = current_contact_id()) THEN co_borrower_dob
            ELSE NULL::date
        END AS co_borrower_dob,
    co_borrower_citizenship,
    co_borrower_marital_status,
    co_borrower_cell_phone,
    co_borrower_home_phone,
    co_borrower_email,
    co_borrower_current_street,
    co_borrower_current_city,
    co_borrower_current_state,
    co_borrower_current_zip,
    co_borrower_housing_type,
    co_borrower_base_income,
    co_borrower_employer,
    co_borrower_employer_phone,
    co_borrower_title,
    co_borrower_start_date,
    co_borrower_decl_bankruptcy,
    co_borrower_decl_foreclosure,
    co_borrower_decl_judgments,
    co_borrower_decl_federal,
    co_borrower_decl_primary,
    borrower_email,
    loan_type,
        CASE
            WHEN is_admin() OR is_borrower() AND (contact_id = current_contact_id() OR co_borrower_contact_id = current_contact_id()) THEN dl_number
            ELSE NULL::text
        END AS dl_number,
    dl_state,
    dl_expiry,
    lo_org,
    lo_nmls_id,
    mismo_imported_at,
    mismo_file_name,
        CASE
            WHEN is_admin() OR is_borrower() AND (contact_id = current_contact_id() OR co_borrower_contact_id = current_contact_id()) THEN mismo_raw_xml
            ELSE NULL::text
        END AS mismo_raw_xml,
    current_interest_rate,
    current_lender,
    current_monthly_payment,
    remaining_loan_balance,
    credit_score,
    monthly_debt,
    borrower_id,
    combined_monthly_income,
    combined_monthly_debt,
    combined_borrower_count,
    loan_term_months,
    amortization_type,
    refinance_purpose,
    pi_payment,
    taxes_monthly,
    insurance_monthly,
    total_pitia,
    cash_to_borrower,
    estimated_closing_costs,
    application_date,
    year_built,
    attachment_type,
    property_estate_type,
    prev_employer_zip,
    prev_employer_phone,
    fee_sheet_scenarios,
    fee_sheet_updated_at,
    fee_sheet_data,
    mi_monthly,
    mi_overridden,
    tax_pct,
    assigned_lender_id,
    quoted_rate,
    quoted_rate_date,
    closed_rate,
    closed_rate_date,
    discount_fee_pct,
    origination_fee_pct,
    preapproval_expiry,
    credit_report_pulled_date,
    rate_lock_expiry,
    locked_rate,
    locked_rate_date,
    borrower_type
   FROM mortgage_applications
  WHERE is_admin() OR is_lead_shared_with_me(contact_id) OR is_lead_shared_with_me(co_borrower_contact_id) OR is_borrower() AND (contact_id = current_contact_id() OR co_borrower_contact_id = current_contact_id());
