/**
 * Cloudflare Worker entry — serves /api/env.js and /config dynamically so
 * secrets come from Cloudflare bindings instead of git.
 * Also blocks access to sensitive paths that were accidentally uploaded.
 */
const BLOCKED_PREFIXES = [
  '/.git',
  '/.github',
  '/.wrangler',
  '/.claude',
  '/.vscode',
  '/.idea',
  '/node_modules',
  '/supabase',
  '/src/',
  '/.gitignore',
  '/.gitattributes',
  '/.assetsignore',
  '/wrangler.toml',
  '/package.json',
  '/package-lock.json',
  '/lender_import.js',
  '/README.md',
];

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const path = url.pathname;

    // === SHORT-LINK REDIRECTOR (/r/{id}) ============================
    // Pretty-URL handler for SMS links generated by track-event v4.
    // Proxies to the Supabase track-event function which logs the click,
    // bumps click_count, fires the lead scorer, then 302s to the
    // destination. Placed at the top so the dashboard / API paths below
    // can't accidentally claim it.
    {
      const segments = path.split('/').filter(Boolean);
      if (request.method === 'GET' && segments[0] === 'r' && segments[1]) {
        const id = segments[1];
        // id is opaque — be strict so junk paths fall through to ASSETS
        if (/^[A-Za-z0-9_-]{1,64}$/.test(id)) {
          const supabaseBase = env.SUPABASE_URL || 'https://ljywhvbmsibwnssxpesh.supabase.co';
          const upstreamUrl = `${supabaseBase}/functions/v1/track-event/t/${id}`;
          try {
            const upstream = await fetch(upstreamUrl, {
              method: 'GET',
              headers: {
                'user-agent': request.headers.get('user-agent') || '',
                'x-forwarded-for':
                  request.headers.get('cf-connecting-ip') ||
                  request.headers.get('x-forwarded-for') || '',
                'referer': request.headers.get('referer') || '',
              },
              redirect: 'manual',
            });
            if (upstream.status === 301 || upstream.status === 302) {
              const location = upstream.headers.get('location');
              if (location) return Response.redirect(location, 302);
            }
            if (upstream.status === 404) {
              return new Response('This link has expired or is invalid.', {
                status: 404,
                headers: { 'content-type': 'text/plain; charset=utf-8' },
              });
            }
            return new Response(await upstream.text(), {
              status: upstream.status,
              headers: { 'content-type': upstream.headers.get('content-type') || 'text/plain' },
            });
          } catch (e) {
            console.error('Short-link /r proxy error:', e);
            return new Response('Link service unavailable.', { status: 502 });
          }
        }
      }
    }
    // === END SHORT-LINK REDIRECTOR =================================

    // Block sensitive paths
    for (const prefix of BLOCKED_PREFIXES) {
      if (path === prefix || path.startsWith(prefix + '/') || path.startsWith(prefix)) {
        return new Response('Not Found', { status: 404 });
      }
    }

    // Block api/env.js static file — always served dynamically
    if (path === '/api/env.js' || path === '/api/env.example.js') {
      if (path === '/api/env.example.js') {
        return new Response('Not Found', { status: 404 });
      }
      const adminEmails = (env.ADMIN_EMAILS || '')
        .split(',').map(s => s.trim()).filter(Boolean);

      const config = {
        SUPABASE_URL: env.SUPABASE_URL || '',
        SUPABASE_ANON_KEY: env.SUPABASE_ANON_KEY || '',
        ADMIN_EMAILS: adminEmails,
        ADMIN_USER_IDS: []
      };

      return new Response(
        'window.APP_CONFIG = ' + JSON.stringify(config) + ';',
        {
          headers: {
            'content-type': 'application/javascript; charset=utf-8',
            'cache-control': 'no-store'
          }
        }
      );
    }

    // Google Maps API key — served to the browser at runtime so it stays in
    // Cloudflare secrets instead of git. Cache in the browser for 5 minutes
    // so page reloads / multiple call sites within a page don't re-hit the
    // worker unnecessarily.
    if (path === '/config') {
      return new Response(
        JSON.stringify({ googleMapsApiKey: env.GOOGLE_MAPS_API_KEY || '' }),
        {
          headers: {
            'content-type': 'application/json; charset=utf-8',
            'cache-control': 'private, max-age=300'
          }
        }
      );
    }

    // Short-link redirect: /s/<slug> → looks up destination via Supabase edge function
    if (path.startsWith('/s/') && path.length > 3) {
      const slug = path.slice(3).replace(/\/$/, '');
      if (slug && /^[a-z0-9]+$/i.test(slug)) {
        try {
          const res = await fetch(`${env.SUPABASE_URL}/functions/v1/short-link`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ action: 'resolve', slug })
          });
          if (res.ok) {
            const data = await res.json();
            if (data.destination_url) {
              return Response.redirect(data.destination_url, 302);
            }
          }
        } catch (e) {
          console.error('Short link resolve error:', e);
        }
        return new Response(
          '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Link not found</title><style>body{font-family:system-ui,sans-serif;background:#0a0a0a;color:#eee;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;text-align:center}h1{color:#C9A84C;margin:0 0 10px;font-size:1.4rem}p{color:#888;font-size:.9rem;margin:0 0 20px}a{color:#C9A84C;text-decoration:none;font-size:.85rem}</style></head><body><div><h1>Rates &amp; Realty</h1><p>This link has expired or doesn\'t exist.</p><a href="/">&larr; Go to homepage</a></div></body></html>',
          { status: 404, headers: { 'content-type': 'text/html; charset=utf-8' } }
        );
      }
    }

    // Clean-URL routing for county area pages (/areas/slug → /areas/slug.html)
    if (/^\/areas\/[a-z0-9-]+$/.test(path)) {
      const newUrl = new URL(request.url);
      newUrl.pathname = path + '.html';
      return withCsp(await env.ASSETS.fetch(new Request(newUrl, request)));
    }

    return withCsp(await env.ASSETS.fetch(request));
  }
};

// Inject a relaxed CSP into HTML responses so pdf.js can spawn its worker
// from a blob: URL. The asset bundler doesn't let us set per-page headers,
// so we layer it on at the worker. Non-HTML responses pass through unchanged.
function withCsp(res) {
  const ct = res.headers.get('content-type') || '';
  if (!ct.includes('text/html')) return res;
  const headers = new Headers(res.headers);
  headers.set(
    'Content-Security-Policy',
    "script-src * 'unsafe-inline' 'unsafe-eval' blob:; worker-src blob: *; child-src blob: *;"
  );
  return new Response(res.body, { status: res.status, statusText: res.statusText, headers });
}
