window.APP_CONFIG = {
  SUPABASE_URL: "https://YOUR-PROJECT.supabase.co",
  SUPABASE_ANON_KEY: "YOUR_SUPABASE_ANON_KEY",
  ADMIN_EMAILS: ["team@example.com"],
  ADMIN_USER_IDS: [],
  MAPBOX_TOKEN: "pk.YOUR_MAPBOX_PUBLIC_TOKEN"
};
